hook.Add( "Initialize", "swrp_bootup", function()
print("Gamemode:\n[STAR WARS RP] by DanK\nLoaded on "..os.date( "%H:%M" ).."\nVersion: 1.6.0")
print("Creating ulx groups!")
RunConsoleCommand("ulx","addgroup ct")
RunConsoleCommand("ulx","addgroup ct-sgt")
RunConsoleCommand("ulx","addgroup ct-lt")
RunConsoleCommand("ulx","addgroup ct-ds")
RunConsoleCommand("ulx","addgroup ct-com")
RunConsoleCommand("ulx","addgroup ctp-trp")
RunConsoleCommand("ulx","addgroup ctp-sgt")
RunConsoleCommand("ulx","addgroup ctp-lt")
RunConsoleCommand("ulx","addgroup ctp-ofc")
RunConsoleCommand("ulx","addgroup ctp-com")
RunConsoleCommand("ulx","addgroup 212th-trp")
RunConsoleCommand("ulx","addgroup 212th-sgt")
RunConsoleCommand("ulx","addgroup 212th-lt")
RunConsoleCommand("ulx","addgroup 212th-heavy")
RunConsoleCommand("ulx","addgroup 212th-com")
RunConsoleCommand("ulx","addgroup 501st-trp")
RunConsoleCommand("ulx","addgroup 501st-sgt")
RunConsoleCommand("ulx","addgroup 501st-lt")
RunConsoleCommand("ulx","addgroup 501st-captain")
RunConsoleCommand("ulx","addgroup 501st-com")
RunConsoleCommand("ulx","addgroup rc-boss")
RunConsoleCommand("ulx","addgroup rc-fixer")
RunConsoleCommand("ulx","addgroup rc-sev")
RunConsoleCommand("ulx","addgroup rc-scorch")
print("All ulx groups created!")
end)