GM.Version = "1.0.0"
GM.Name = "Star Wars RP 2"
GM.Author = "By SWRP2"

DeriveGamemode("sandbox")
DEFINE_BASECLASS("gamemode_sandbox")

GM.Sandbox = BaseClass
if CLIENT then
local job = "[ERROR]"
net.Receive("SWRPCurrentJob",function(len, ply)
	job = net.ReadString()
end)
net.Receive("OpenF4Menu",function(len, ply)
	function UpdatePage()
	page = LocalPlayer():GetNWInt("CurrentPage")
	end
	UpdatePage()
	f4Msg = net.ReadString()
	local version = "1.7.0"
	local frame = vgui.Create( "DFrame" )
	frame:SetSize( ScrW() * .8, ScrH() * .8 )
	frame:Center()
	frame:SetDraggable( false )
	frame:ShowCloseButton( true )
	frame:MakePopup()
	frame:SetTitle("Choose a job | Star Wars RP Version "..version)
	frame.Paint = function()
		surface.SetDrawColor(60, 60, 60, 255)
		surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())

		surface.SetDrawColor(40, 40, 40, 255)
		surface.DrawRect(0, 24, frame:GetWide(), 1)
		surface.SetDrawColor(40, 40, 40, 255)
		surface.DrawRect(120, 24, 10, frame:GetTall())
	end
	but_entry = vgui.Create("DButton", frame)
		but_entry:SetSize(120, 20)
		but_entry:SetPos(0, 25)
		but_entry:SetText("Standard")
		but_entry.DoClick = function()
			LocalPlayer():SetNWInt("CurrentPage",1)
			page = LocalPlayer():GetNWInt("CurrentPage")
			frame:Close()
			net.Start("SWRPReOpenF4")
			net.SendToServer()
		end
	but_entry = vgui.Create("DButton", frame)
		but_entry:SetSize(120, 20)
		but_entry:SetPos(0, 45)
		but_entry:SetText("CT")
		but_entry.DoClick = function()
			LocalPlayer():SetNWInt("CurrentPage",2)
			page = LocalPlayer():GetNWInt("CurrentPage")
			frame:Close()
			net.Start("SWRPReOpenF4")
			net.SendToServer()
		end
	but_entry = vgui.Create("DButton", frame)
		but_entry:SetSize(120, 20)
		but_entry:SetPos(0, 65)
		but_entry:SetText("CTP")
		but_entry.DoClick = function()
			LocalPlayer():SetNWInt("CurrentPage",3)
			page = LocalPlayer():GetNWInt("CurrentPage")
			frame:Close()
			net.Start("SWRPReOpenF4")
			net.SendToServer()
		end
	but_entry = vgui.Create("DButton", frame)
		but_entry:SetSize(120, 20)
		but_entry:SetPos(0, 85)
		but_entry:SetText("212th")
		but_entry.DoClick = function()
			LocalPlayer():SetNWInt("CurrentPage",4)
			page = LocalPlayer():GetNWInt("CurrentPage")
			frame:Close()
			net.Start("SWRPReOpenF4")
			net.SendToServer()
		end
	but_entry = vgui.Create("DButton", frame)
		but_entry:SetSize(120, 20)
		but_entry:SetPos(0, 105)
		but_entry:SetText("501st")
		but_entry.DoClick = function()
			LocalPlayer():SetNWInt("CurrentPage",5)
			page = LocalPlayer():GetNWInt("CurrentPage")
			frame:Close()
			net.Start("SWRPReOpenF4")
			net.SendToServer()
		end
	but_entry = vgui.Create("DButton", frame)
		but_entry:SetSize(120, 20)
		but_entry:SetPos(0, 125)
		but_entry:SetText("Republic Commando")
		but_entry.DoClick = function()
			LocalPlayer():SetNWInt("CurrentPage",6)
			page = LocalPlayer():GetNWInt("CurrentPage")
			frame:Close()
			net.Start("SWRPReOpenF4")
			net.SendToServer()
		end
	if (page == 1) then
		local icon = vgui.Create( "DModelPanel", frame )
		icon:SetPos(130,70)
		icon:SetSize( 130, 150 )
		icon:SetModel( "models/player/clone/baldcadet.mdl" )
		but_entry = vgui.Create("DButton", frame)
				but_entry:SetSize(130, 20)
				but_entry:SetPos(130,220)
				but_entry:SetText("Become Cadet")
				but_entry.DoClick = function()
					net.Start("SWRPMsg")
					net.WriteString("Cadet")
					net.SendToServer()
					frame:Close()
				end
				but_entry.Paint = function()
					surface.SetDrawColor(255, 255, 255, 255)
					surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
				end
	elseif (page == 2) then
		local icon = vgui.Create( "DModelPanel", frame )
		icon:SetPos(130,70)
		icon:SetSize( 130, 150 )
		icon:SetModel( "models/player/testp2c/cgi ctp2.mdl" )
		but_entry = vgui.Create("DButton", frame)
				but_entry:SetSize(130, 20)
				but_entry:SetPos(130,220)
				but_entry:SetText("Become CT")
				but_entry.DoClick = function()
					net.Start("SWRPMsg")
					net.WriteString("CT")
					net.SendToServer()
				frame:Close()
				end
				but_entry.Paint = function()
					surface.SetDrawColor(255, 255, 255, 255)
					surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
				end
		local icon = vgui.Create( "DModelPanel", frame )
		icon:SetPos(260,70)
		icon:SetSize( 130, 150 )
		icon:SetModel( "models/player/clone_trooper_ranks/green.mdl" )
		but_entry = vgui.Create("DButton", frame)
				but_entry:SetSize(130, 20)
				but_entry:SetPos(260,220)
				but_entry:SetText("Become CT Sergeant")
				but_entry.DoClick = function()
					net.Start("SWRPMsg")
					net.WriteString("CT Sergeant")
					net.SendToServer()
				frame:Close()
				end
				but_entry.Paint = function()
					surface.SetDrawColor(255, 255, 255, 255)
					surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
				end
		local icon = vgui.Create( "DModelPanel", frame )
		icon:SetPos(390,70)
		icon:SetSize( 130, 150 )
		icon:SetModel( "models/player/clone_trooper_ranks/blue.mdl" )
		but_entry = vgui.Create("DButton", frame)
				but_entry:SetSize(130, 20)
				but_entry:SetPos(390,220)
				but_entry:SetText("Become CT Lieutenant")
				but_entry.DoClick = function()
					net.Start("SWRPMsg")
					net.WriteString("CT Lieutenant")
					net.SendToServer()
				frame:Close()
				end
				but_entry.Paint = function()
					surface.SetDrawColor(255, 255, 255, 255)
					surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
				end
		local icon = vgui.Create( "DModelPanel", frame )
		icon:SetPos(520,70)
		icon:SetSize( 130, 150 )
		icon:SetModel( "models/player/clone/ctofficer.mdl" )
		but_entry = vgui.Create("DButton", frame)
				but_entry:SetSize(130, 20)
				but_entry:SetPos(520,220)
				but_entry:SetText("Become CT Drill Sergeant")
				but_entry.DoClick = function()
					net.Start("SWRPMsg")
					net.WriteString("CT Drill Sergeant")
					net.SendToServer()
				frame:Close()
				end
				but_entry.Paint = function()
					surface.SetDrawColor(255, 255, 255, 255)
					surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
				end		
		local icon = vgui.Create( "DModelPanel", frame )
		icon:SetPos(650,70)
		icon:SetSize( 130, 150 )
		icon:SetModel( "models/player/clone/ctnco.mdl" )
		but_entry = vgui.Create("DButton", frame)
				but_entry:SetSize(130, 20)
				but_entry:SetPos(650,220)
				but_entry:SetText("Become CT Commander")
				but_entry.DoClick = function()
					net.Start("SWRPMsg")
					net.WriteString("CT Commander")
					net.SendToServer()
				frame:Close()
				end
				but_entry.Paint = function()
					surface.SetDrawColor(255, 255, 255, 255)
					surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
				end
	elseif (page == 3) then
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(10,90)
			but_entry:SetText("Become CTP")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("CTP")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(130,90)
			but_entry:SetText("Become CTP Sergeant")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("CTP Sergeant")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(250,90)
			but_entry:SetText("Become CTP Lieutenant")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("CTP Lieutenant")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(370,90)
			but_entry:SetText("Become CTP Officer")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("CTP Officer")
				net.SendToServer()
			frame:Close()
			end	
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end	
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(130, 20)
			but_entry:SetPos(490,90)
			but_entry:SetText("Become CTP Commander")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("CTP Commander")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	elseif (page == 4) then
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(10,110)
			but_entry:SetText("Become 212th Trooper")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("212th Trooper")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(130,110)
			but_entry:SetText("Become 212th Sergeant")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("212th Sergeant")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(250,110)
			but_entry:SetText("Become 212th Lieutenant")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("212th Lieutenant")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(370,110)
			but_entry:SetText("Become 212th Heavy")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("212th Heavy")
				net.SendToServer()
			frame:Close()
			end	
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end	
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(130, 20)
			but_entry:SetPos(490,110)
			but_entry:SetText("Become 212th Commander")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("212th Commander")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	elseif (page == 5) then
		but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(10,130)
			but_entry:SetText("Become 501st Trooper")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("501st Trooper")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(130,130)
			but_entry:SetText("Become 501st Sergeant")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("501st Sergeant")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(250,130)
			but_entry:SetText("Become 501st Lieutenant")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("501st Lieutenant")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(370,130)
			but_entry:SetText("Become 501st Captain")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("501st Captain")
				net.SendToServer()
			frame:Close()
			end	
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end	
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(130, 20)
			but_entry:SetPos(490,130)
			but_entry:SetText("Become 501st Commander")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("501st Commander")
				net.SendToServer()
			frame:Close()
			end	
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	elseif (page == 6) then
		but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(10,150)
			but_entry:SetText("Become RC Scorch")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("RC Scorch")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(130,150)
			but_entry:SetText("Become RC Sev")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("RC Sev")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(250,150)
			but_entry:SetText("Become RC Fixer")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("RC Fixer")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	but_entry = vgui.Create("DButton", frame)
			but_entry:SetSize(120, 20)
			but_entry:SetPos(370,150)
			but_entry:SetText("Become RC Boss")
			but_entry.DoClick = function()
				net.Start("SWRPMsg")
				net.WriteString("RC Boss")
				net.SendToServer()
			frame:Close()
			end
			but_entry.Paint = function()
				surface.SetDrawColor(255, 255, 255, 255)
				surface.DrawRect(0,0,frame:GetWide(),frame:GetTall())
			end
	elseif (page == nil) then
		print("Error")
		LocalPlayer():SetNWInt("CurrentPage",1)
		frame:Close()
	end
	local infotext = vgui.Create( "RichText", frame )
			infotext:SetSize(200,20)
			infotext:SetPos(450,30)
			infotext:SetText("Current Regiment: "..LocalPlayer():GetNWString("CurrentRegiment"))
	local infotext = vgui.Create( "RichText", frame )
			infotext:SetSize(200,20)
			infotext:SetPos(450,60)
			infotext:SetText("Current Page: "..page)
end)


concommand.Add("job",function(ply, command, args) 
	job = tostring(args[1])
	net.Start("SWRPMsg")
				net.WriteString(job)
	net.SendToServer()
end)
end